name: Process Answer

on:
  repository_dispatch:
    types: [answer]

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR SHA
        id: pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const issue_number = parseInt('${{ github.event.client_payload.issue }}', 10);
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issue_number
            });
            return pr.data.head.sha;

      - name: Set commit status
        uses: ouzi-dev/commit-status@v2
        with:
          sha: ${{ steps.pr.outputs.result }}
          state: ${{ github.event.client_payload.command == 'answer yes' && 'success' || 'failure' }}
          context: discrimination-check
          description: ${{ github.event.client_payload.command == 'answer yes' && 'Answered yes' || 'Answered no' }}
