name: Handle /answer command

on:
  issue_comment:
    types: [created]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  slash-command:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: answer
          permission: write
