name: Process PR Answer

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  process-answer:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Trigger only on `/answer` command
        uses: actions-cool/pull-request-comment-trigger@v1.2.0
        with:
          trigger: '/answer'
          prefix_only: true
          reaction: true

      - name: Debug comment body
        run: echo "Comment body: ${{ github.event.comment.body }}"

      - name: Get PR commit SHA
        id: pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.head.sha;

      - name: Show PR SHA
        run: echo "SHA: ${{ steps.pr.outputs.result }}"

      - name: Set commit status (success)
        if: github.event.comment.body == '/answer yes'
        uses: ouzi-dev/commit-status@v2
        with:
          sha: ${{ steps.pr.outputs.result }}
          state: success
          context: discrimination-check
          description: Answered yes

      - name: Set commit status (failure)
        if: github.event.comment.body == '/answer no'
        uses: ouzi-dev/commit-status@v2
        with:
          sha: ${{ steps.pr.outputs.result }}
          state: failure
          context: discrimination-check
          description: Answered no
