name: Process PR Answer

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  trigger-on-answer:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null
    steps:
      - name: Check for valid answers
        uses: actions-cool/pull-request-comment-trigger@v1.2.0
        with:
          trigger: '/answer'
          prefix_only: true
          reaction: true

      - name: Set commit status based on answer
        if: github.event.comment.body == '/answer yes' || github.event.comment.body == '/answer no'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body.trim().toLowerCase();
            const pull_number = context.issue.number;
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number
            });

            const sha = pr.data.head.sha;

            const status = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              context: 'discrimination-check',
              state: comment === '/answer yes' ? 'success' : 'failure',
              description: comment === '/answer yes' ? 'Answered yes' : 'Answered no'
            };

            await github.rest.repos.createCommitStatus(status);
