name: Process PR Answers

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  statuses: write

jobs:
  process-answer:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Respond to comment command
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body.toLowerCase();
            const pr = context.payload.issue.pull_request;

            const sha = (await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })).data.head.sha;

            let status = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              context: 'style-guide-check',
              state: 'pending',
              description: 'Waiting for answer...'
            };

            if (comment.includes('/answer yes')) {
              status.state = 'success';
              status.description = 'Answered yes';
            } else if (comment.includes('/answer no')) {
              status.state = 'failure';
              status.description = 'Answered no';
            } else {
              return;
            }

            await github.rest.repos.createCommitStatus(status);
